name: cd
on:
  push:
    tags: [ "*" ]
 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "List files"
        run: ls -la

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: jerem14
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: "Push if on tag"
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./
          tags: "jerem14/sayhello:${{ github.ref_name }}"