# cd.yml
name: cd
on:
  push:
    tags: [ "*" ]
 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: ls -la
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: contains('refs/heads/main', github.ref)
        with:
          username: jerem14
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: "Push if on `main`"
        uses: docker/build-push-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          context: ./
          tags: "jerem14/sayhello:${{ github.ref_name }}"