name: ci-cd
on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Lint Dockerfile"
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile

      - name: "Build Docker image"
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: false
          tags: "jerem14/sayhello:test"
          load: true

      - name: "Test image - Display README"
        run: |
          docker run --rm jerem14/sayhello:test cat README.md

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: jerem14
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: "Push unstable if on main branch"
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/main'
        with:
          push: true
          context: ./
          tags: "jerem14/sayhello:unstable"

      - name: "Push if tag"
        uses: docker/build-push-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          context: ./
          tags: "jerem14/sayhello:${{ github.ref_name }}"